---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7
  - name: debian-8

suites:
  - name: butterfly
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[butterfly]
      - recipe[butterfly::libsass]
  - name: butterfly-service
    excludes:
      - ubuntu-12.04
      - debian-7
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[butterfly]
      - recipe[butterfly::systemd]
