---
driver:
  name: docker
  binary: docker
  use_sudo: false

provisioner:
  name: chef_zero
  chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[locales]
  - name: ubuntu-18.04
  - name: debian-9
  - name: debian-10

suites:
  - name: butterfly
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[butterfly]
      - recipe[butterfly::libsass]
  - name: butterfly-service
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[butterfly]
      - recipe[butterfly::systemd]
    excludes:
      - debian-9
      - debian-10
      - ubuntu-16.04
      - ubuntu-18.04
